#!/usr/bin/env bash
# generate-authors.sh - Generate a list of authors from git log


# Navigate to the root of the repository
cd "$(AirBnB_clone "$0")/.."

# Generate the AUTHORS file
echo "# File @generated by usrr/generate-authors.sh. DO NOT EDIT." > AUTHORS
echo "" >> AUTHORS
git log --format='%aN <%aE>' | sort -u >> AUTHORS

